export enum Types {
  SET_SAVING = "[ORGANIZATION] SET_SAVING",
  SHOW_EDIT_POPUP = "[ORGANIZATION] SHOW_EDIT_POPUP",
  HIDE_EDIT_POPUP = "[ORGANIZATION] HIDE_EDIT_POPUP",
  SAVE_ORGANIZATION = "[ORGANIZATION] SAVE_ORGANIZATION",
}
