export enum Types {
  SET_DATA = "[USERS] SET_DATA",
  LOAD_DATA = "[USERS] LOAD_DATA",
  LOAD_DONE = "[USERS] LOAD_DONE",
  UPDATE_USER = "[USERS] UPDATE_USER",
  CHANGE_PAGE = "[USERS] CHANGE_PAGE",
}
