export enum Types {
  SET_SAVING = "[USER] SET_SAVING",
  SHOW_EDIT_POPUP = "[USER] SHOW_EDIT_POPUP",
  HIDE_EDIT_POPUP = "[USER] HIDE_EDIT_POPUP",
  SET_USER = "[USER] SET_USER",
  SAVE_USER = "[USER] SAVE_USER",
}
