export enum Types {
  SET_DATA = "[ORGANIZATIONS] SET_DATA",
  LOAD_DATA = "[ORGANIZATIONS] LOAD_DATA",
  UPDATE_ORGANIZATION = "[ORGANIZATIONS] UPDATE_ORGANIZATION",
  SELECT_ORGANIZATION = "[ORGANIZATIONS] SELECT_ORGANIZATION",
}
